# Generated by Django 4.2.27 on 2026-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight_class', models.CharField(blank=True, max_length=100)),
                ('reach', models.PositiveIntegerField(blank=True, null=True)),
                ('stance', models.CharField(blank=True, max_length=50)),
                ('record', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
