# Generated by Django 4.2.27 on 2026-01-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=200)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='events.event')),
                ('fighter_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_a', to='fighters.fighter')),
                ('fighter_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_b', to='fighters.fighter')),
            ],
        ),
    ]
