# Generated by Django 4.2.27 on 2026-01-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_events', to='events.fight')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_events', to='fighters.fighter')),
            ],
        ),
    ]
